config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :users
  resources :sessions
  resources :articles do
    resources :comments
    resources :votes
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  attr_accessor :password
  before_save :encrypt_password


  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates :email, presence:true, uniqueness:true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "entered is not correct "}
  validates :password, length: { minimum: 3 }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
   if password.present?
     self.password_salt = BCrypt::Engine.generate_salt
     self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
   end
 end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :admin?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def admin?
    return true if current_user.email == "admin@spherebyte.in"
  end

  def login_required
    redirect_to new_session_path unless current_user
  end

  def find_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :login_required

  def show
    @article = Article.find(params[:id])
    @vote = @article.votes.find_by_voter(current_user.id)
    @voted = false
    @article.votes.each do |vote|
      if vote.voter.to_i == current_user.id.to_i
        @voted = true
      end
    end
  end

  def new
      @article = current_user.articles.new
  end

  def edit
      @article = @current_user.articles.find(params[:id])
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article
    else
      render "new"
    end
  end

  def update
      @article = current_user.articles.find(params[:id])
      if @article.update(article_params)
        redirect_to @article
      else
        render "edit"
      end
  end

  def destroy
      @article = current_user.articles.find(params[:id])
      @article.destroy

      redirect_to users_path
  end


  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_article
  def create
    @comment = @article.comments.new(comment_params)
    @comment.commenter = current_user.email
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to users_path
    end
  end

  def create
      user = User.authenticate(params[:email], params[:password])
      if user
        session[:user_id] = user.id
        redirect_to users_path
      else
        @error_login = "Invalid email or password"
        render "new"
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]
  before_filter :find_user, :except => [:index, :new, :create]

  def show
      @articles = @user.articles.last(5)
  end

  def index
      @user = User.all
      @articles = Article.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    if current_user
      redirect_to users_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
      if @user.update_attributes(user_params)
        redirect_to @user
      else
        render 'edit'
      end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :mob, :age)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :find_article
  def create
    @votes = @article.votes.new
    @votes.voter = current_user.id
    @votes.save
    redirect_to article_path(@article)
  end
  def destroy
    @votes = @article.votes.find(params[:id])
    @votes.destroy
    redirect_to article_path(@article)


  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to users_path
    else
      render :layout => 'welcome_layout'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for([@article]) do |f| %>
<% if @article.errors.any? %>
  <div class = "alert alert-warning">
    <h3><%= pluralize(@article.errors.count, "Error") %>
    prohibited this article from saving</h3>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>
<table >
  <tr>
    <td><%= f.text_field :title, class: "form-control", :placeholder => "Title" %></td>
  </tr>
  <tr>
    <td><%= f.text_area :text, class: "form-control text_area", :placeholder => "Blog", size: "50x30" %></td>
  </tr>
  <tr>
    <td><%= f.submit :submit.capitalize, :class => "btn btn-primary", :value => "Post" %></td>
  </tr>
</table>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<p>
  <h1><%= truncate(@article.title) %></h1>
  created by <strong><%= link_to @article.user.email, user_path(@article.user.id) %></strong>
    <div class="info_text">
      (Last updated on <%= @article.updated_at.strftime("%b %d, %Y") %>)
    </div>
</p>

<!-- Displays Article Here -->

  <div class="well article">
    <%= @article.text %>
  </div>

  <!-------------------------->
<div class="row">
  <div class="col-sm-12">
    <div class="col-sm-4"></div>
    <div class="col-sm-8">
      <% if current_user.id == @article.user_id %>
        <%= link_to  '<i class="glyphicon glyphicon-pencil"></i>&nbsp;Edit'.html_safe, edit_article_path(@article), :class => "btn btn-info"  %>
      <% end %>
      <!-- Votting for Blogs -->
      <div class= "vote">
        <% unless @voted %>
                <%= form_for ([@article, @article.votes.build]) do |f| %>
                    <%= button_tag(type: 'submit', class: "btn btn-like") do %>
                      <%= @article.votes.count %>
                      <span class="glyphicon glyphicon-thumbs-up">&nbsp;like</span>
                      <% end %>
                <% end %>
        <% else %>
            <%= render @article.votes.find_by_voter(current_user.id) %>
        <% end %>
      </div>
      <!---------------------------------->
    </div>
  </div>
</div>

<div class = "well">

  <h4><%=pluralize(@article.comments.count, 'comment') %> </h4>
  <ul class="list-group">
      <%= render @article.comments.reverse %>
  </ul>
  <%= render 'comments/form' %>
</div>

<% if @article.user_id == current_user.id %>
<div class="col-sm-12"> <%= link_to "Delete Article", article_path(@article),class: "btn btn-danger btn-block", method: :delete, data: {confirm: "Are you sure? "} %></div>
<% else %>
<div class="col-sm-12"> <%= link_to "Delete Article", article_path(@article),class: "btn btn-danger btn-block disabled", method: :delete, data: {confirm: "Are you sure? "} %></div>
<% end %>

app/views/comments/_comment.html.erb
<li class="list-group-item">
<table>
  <tr>
    <td><span class="glyphicon glyphicon-user"></span></td>
    <% if comment.commenter  == current_user.email %>
    <td><%=  link_to comment.commenter, user_path(current_user.id)%></td>
    <% else %>
     <td><%=  link_to comment.commenter, user_path(@article.user_id)%></td>
    <% end %>
  </tr>
  <tr>
    <td><strong>Comment:&nbsp;&nbsp;</strong></td>
    <td><%= comment.body %></td>
    <td>
      <% if comment.commenter.to_s ==  current_user.email.to_s then %>
      <%= link_to 'delete', [comment.article, comment],
                method: :delete, class: 'btn btn-danger btn-xs ' ,
                data: { confirm: 'Are you sure?' } %>
      <% end %>

    </td>
    <td>
      <% if admin? %>
      <%= link_to 'delete', [comment.article, comment],
                method: :delete, class: 'btn btn-danger btn-xs ' ,
                data: { confirm: 'Are you sure?' } %>

      <% end %>
    </td>

  </tr>

</table>

</li>

app/views/comments/_form.html.erb
<%= form_for ([@article, @article.comments.build]) do |f| %>
<table >
  <tr>
    <td><%= f.text_area :body, class: "form-control", :placeholder => "Add comment" %></td>
    <td><%= f.submit :submit.capitalize, :class => "btn btn-primary", :value => "Post" %></td>
  </tr>

</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Sphere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to '<i class="glyphicon glyphicon-globe"></i> Blog Sphere'.html_safe,users_path, :class => "navbar-brand" %>
          </div>
          <ul class="nav navbar-nav navbar-right">

        <% if current_user %>

          <li><%= link_to current_user.email, user_path(current_user) %></a></li>
          <li><%= link_to '<i class="glyphicon glyphicon-log-out"></i> Logout'.html_safe, log_out_path %></li>

        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe, new_session_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i> SignUp'.html_safe, new_user_path %></li>
        <% end %>

      </ul>
        </div>
      </nav>
      <div class="col-sm-9"><%= yield %></div>
      <% if current_user %>
      <div class="col-sm-3"><%= link_to  '<i class="glyphicon glyphicon-pencil"></i> New Article'.html_safe, new_article_path, class: "btn btn-primary"  %>
      </div>
      <% end %>

    </div>




  </div>

  <nav class="navbar navbar-inverse navbar-fixed-bottom">


  </nav>


</body>
</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Sphere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid welcome_container">
    <div class="row">
      <div class="col-md-6">
        <div class="welcome_links">
          <%= link_to "Try out", new_user_path, :class => "btn btn-primary btn-block btn-lg" %><br \>
          <%= link_to "Already member ? ", new_session_path, :class => "btn btn-link" %>

        </div>

      </div>
      <div class="col-md-6">
        <div class="intro">
           Welcome To Blog Sphere
        </div>
      </div>

    </div>

    </div>
</body>
</html>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <center><h1>Edit Profile</h1></center>
  </div>
  <div class="col-sm-12 profile">
    <div class="col-sm-4 profile_contents">
      <% if @user.profiledp == nil %>
        <img src="../../andrew.png" class="img-circle" alt="Cinque Terre" width="250" height="250">
      <% else %>
        <img src="../../<%= @user.profiledp %>" class= "img-circle" alt="<%= @user.name %>" width="250" height="250">
      <% end %>
    </div>
    <div class="col-sm-8">
      <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class = "alert alert-warning">
          <h3><%= pluralize(@user.errors.count, "Error") %>
          prohibited editing profile.</h3>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
          </ul>
        </div>
      <% end %>
            <table class = "table prof">
              <tr><td class="labl"><%= f.label :email%></td><td><%= f.text_field :email, class: "form-control" %></td></tr>
              <tr><td class ="labl"><%= f.label :password%></td><td><%= f.password_field :password, class: "form-control" %></td></tr>
              <tr><td class ="labl"><%= f.label :name%></td><td><%= f.text_field :name, class: "form-control" %></td></tr>
              <tr><td class ="labl"><%= f.label :mob%></td><td><%= f.text_field :mob, class: "form-control" %></td></tr>
              <tr><td class ="labl"><%= f.label :age%></td><td><%= f.text_field :age, class: "form-control" %></td></tr>
              <tr><td class ="labl"></td><td><%= f.submit :submit, :class => "btn btn-primary ", :value => "Save" %></td></tr>
            </table>
      <% end %>

    </div>

  </div>



</div>

app/views/users/index.html.erb
<table class= "table tbl-list">
  <% @articles.each do|article| %>
    <tr>
      <td>
        <small><%= article.created_at.strftime("%b %d, %Y") %></small>
      </td>
      <td>
         <%= link_to truncate(article.title), article_path(article) %>
      </td>

        <% if current_user.id == article.user_id || admin? %>
          <td>
            <%= link_to  '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_article_path(article)  %>
          </td>
          <td>
            <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, article_path(article), method: :delete, data: {confirm: "Are you sure? "} %>
          </td>
        <% end %>

      <td>
        <% if admin? %>
          <%= link_to '<i class="glyphicon glyphicon-user"></i>'.html_safe, user_path(article.user_id) %>
        <% end %>
      </td>
    </tr>
  <% end %>

</table>

<%= will_paginate @articles %>

app/views/users/new.html.erb
<div class = "col-sm-6 col-sm-offset-4">
<%= form_for @user,:html => {:multipart => true}  do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-info">
      <h2>Sign Up Error </h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email, class: "form-control", placeholder: "E-Mail" %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password, class: "form-control", placeholder: "**********" %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "**********"%>
    <%= f.submit :submit, value:"SignUp", class: "btn btn-success" %>
  </p>

<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <center><h1>Profile</h1></center>
  </div>
  <div class="col-sm-12 profile">
    <div class="col-sm-4 profile_contents">
      <% if @user.profiledp == nil %>
        <img src="../andrew.png" class="img-circle" alt="Cinque Terre" width="250" height="250">
      <% else %>
        <img src="../<%= @user.profiledp %>" class= "img-circle" alt="<%= @user.name %>" width="250" height="250">
      <% end %>
      <center>
        <% if @user.id == current_user.id %>
          <%= link_to  '<i class="glyphicon glyphicon-pencil"></i>Edit Profile'.html_safe, edit_user_path(@user), class: "btn btn-primary btn-block profile_edit"  %>
        <% end %>
      </center>
    </div>
    <div class="col-sm-8">
      <table class = "table prof">
        <tr><td class="labl">Email : </td><td><%= @user.email %></td></tr>
        <tr><td class ="labl">Name : </td><td><%= @user.name %></td></tr>
        <tr><td class ="labl">Mobile : </td><td><%= @user.mob %></td></tr>
        <tr><td class ="labl">Age : </td><td><%= @user.age %></td></tr>
        <tr> <td class ="labl">Total articles :</td><td><%= @articles.count %></td></tr>
        <tr> <td class ="labl">Articles : </td>
              <td>
                <% @articles.each do |article| %>
                  <%= link_to truncate(article.title), article_path(article.id) %><br />
                <% end %>
              </td>
        </tr>
      </table>

    </div>

  </div>



</div>

app/views/votes/_vote.html.erb
<%= form_for ([vote.article, vote]), :html => {:method => :delete} do |f| %>
    <%= button_tag(type: 'submit', class: "btn btn-like") do %>
      <%= @article.votes.count %>
      <span class="glyphicon glyphicon-thumbs-down">&nbsp;Unlike</span>
      <% end %>
<% end %>